### ISSUE TITLE
next will throw error

### ISSUE THREAD

**Issue by tianyingchun** [zemd/eslint-flat-config#14]
TypeError: context.getAncestors is not a function
 
Rule: "@next/next/no-page-custom-font"

**Comment by zemd** [comment]
hey @tianyingchun thanks for the creating issue. quick question - what version of eslint are you using?

**Comment by tianyingchun** [comment]
V9

**Comment by zemd** [comment]
@tianyingchun at the moment, the package does not support eslint v9. there is a PR https://github.com/zemd/eslint-flat-config/pull/13 that updates all dependencies to support v9, but not all dependencies support it yet.
